# Generated by Django 4.2.13 on 2024-07-02 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbladdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField()),
                ('address_type', models.CharField(max_length=1)),
                ('address', models.CharField(max_length=255)),
                ('city_id', models.IntegerField()),
                ('state_id', models.IntegerField()),
                ('country_id', models.IntegerField()),
                ('zipcode', models.IntegerField()),
            ],
            options={
                'db_table': 'tbladdress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcv',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(blank=True, max_length=100, null=True)),
                ('lname', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=100)),
                ('email2', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=22)),
                ('phone2', models.CharField(blank=True, max_length=22, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('nationality_id', models.IntegerField()),
                ('fathername', models.CharField(blank=True, max_length=100, null=True)),
                ('mothername', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.CharField(blank=True, max_length=128, null=True)),
                ('aadharno', models.CharField(blank=True, max_length=16, null=True)),
                ('panno', models.CharField(blank=True, max_length=10, null=True)),
                ('isvalidpassport', models.IntegerField()),
                ('passportno', models.CharField(blank=True, max_length=30, null=True)),
                ('issuecountry', models.CharField(blank=True, max_length=30, null=True)),
                ('expirydate', models.DateField(blank=True, null=True)),
                ('profileimage', models.CharField(blank=True, max_length=100, null=True)),
                ('is_online', models.IntegerField()),
                ('onlinesource', models.CharField(blank=True, max_length=16, null=True)),
                ('status', models.IntegerField()),
                ('verified_by', models.IntegerField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('contacted_by', models.IntegerField(blank=True, null=True)),
                ('lastviewed_by', models.IntegerField(blank=True, null=True)),
                ('lastviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblcv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblcvfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=64)),
                ('candidate_id', models.IntegerField()),
                ('resume_text', models.IntegerField()),
                ('created_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblcvfiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbleducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField()),
                ('qualification_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('subject_id', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=64)),
                ('specialization', models.CharField(blank=True, max_length=50, null=True)),
                ('institute', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('yearpassed', models.CharField(blank=True, max_length=20, null=True)),
                ('percentage', models.CharField(blank=True, max_length=20, null=True)),
                ('edumode_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbleducation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbledulevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edulevel', models.CharField(max_length=100)),
                ('is_active', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('modified_by', models.IntegerField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbledulevel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblinstitutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institutename', models.CharField(max_length=400)),
                ('is_active', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('modified_by', models.IntegerField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tblinstitutes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbllanguage_gen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=100)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbllanguages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tbluniversities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univname', models.CharField(max_length=100)),
                ('is_active', models.IntegerField()),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbluniversities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='names_master',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'indian_male_names',
            },
        ),
        migrations.CreateModel(
            name='pincode_master',
            fields=[
                ('pincode', models.IntegerField()),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pincode_dataset',
            },
        ),
        migrations.CreateModel(
            name='Tblcities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('state_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tblcities',
            },
        ),
        migrations.CreateModel(
            name='Tblcompany_master',
            fields=[
                ('fld_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=1)),
                ('bd_com_master_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_master',
            },
        ),
        migrations.CreateModel(
            name='Tblcontractmode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractmode', models.CharField(max_length=20)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.IntegerField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblcontractmode',
            },
        ),
        migrations.CreateModel(
            name='Tblcountries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortname', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=150)),
                ('phonecode', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblcountries',
            },
        ),
        migrations.CreateModel(
            name='Tblcvkeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField()),
                ('industries', models.CharField(max_length=128)),
                ('sectors', models.CharField(max_length=256)),
                ('phases', models.CharField(max_length=256)),
                ('keywords', models.TextField()),
            ],
            options={
                'db_table': 'tblcvkeywords',
            },
        ),
        migrations.CreateModel(
            name='Tbldegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degreename', models.CharField(max_length=50)),
                ('edulevel_id', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbldegree',
            },
        ),
        migrations.CreateModel(
            name='Tbldesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbldesignation',
            },
        ),
        migrations.CreateModel(
            name='Tbledumode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edumode', models.CharField(max_length=30)),
                ('is_active', models.IntegerField()),
                ('created_by', models.IntegerField()),
                ('modified_by', models.IntegerField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tbledumode',
            },
        ),
        migrations.CreateModel(
            name='Tblexperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField()),
                ('companyname', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField(blank=True, null=True)),
                ('designation_id', models.IntegerField(blank=True, null=True)),
                ('country_id', models.IntegerField()),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('tottalexp', models.IntegerField(blank=True, null=True)),
                ('employmentnature', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'tblexperience',
            },
        ),
        migrations.CreateModel(
            name='Tblfundagencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencyname', models.CharField(max_length=100)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.IntegerField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblfundagencies',
            },
        ),
        migrations.CreateModel(
            name='Tblfundedproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('projectname', models.TextField()),
                ('projdesig', models.CharField(blank=True, max_length=50, null=True)),
                ('compdesig', models.CharField(blank=True, max_length=50, null=True)),
                ('industry_id', models.IntegerField()),
                ('sector_id', models.IntegerField()),
                ('phase_id', models.IntegerField()),
                ('employername', models.CharField(max_length=100)),
                ('natureemployer', models.CharField(max_length=1)),
                ('projectexp', models.CharField(max_length=30)),
                ('country_id', models.IntegerField()),
                ('state_id', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('projectlength', models.IntegerField(blank=True, null=True)),
                ('lane', models.IntegerField(blank=True, null=True)),
                ('projectcost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('clientname', models.CharField(blank=True, max_length=100, null=True)),
                ('fundingagency_id', models.IntegerField()),
                ('contractmode_id', models.IntegerField(blank=True, null=True)),
                ('pavement_id', models.IntegerField(blank=True, null=True)),
                ('terrain_id', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblfundedproject',
            },
        ),
        migrations.CreateModel(
            name='Tblindustry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industryname', models.CharField(max_length=100)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblindustry',
            },
        ),
        migrations.CreateModel(
            name='Tblkeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('sector_id', models.IntegerField()),
                ('phase_id', models.IntegerField()),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblkeywords',
            },
        ),
        migrations.CreateModel(
            name='Tblpavement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavementname', models.CharField(max_length=50)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.IntegerField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblpavement',
            },
        ),
        migrations.CreateModel(
            name='Tblphase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phasename', models.CharField(max_length=100)),
                ('sector_id', models.IntegerField()),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblphase',
            },
        ),
        migrations.CreateModel(
            name='Tblprodetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fun_tbl_id', models.IntegerField()),
                ('sector', models.CharField(max_length=255)),
                ('phase', models.CharField(max_length=255)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funded_by', models.CharField(max_length=255)),
                ('contractmode', models.CharField(max_length=125)),
            ],
            options={
                'db_table': 'tbl_project_detail',
            },
        ),
        migrations.CreateModel(
            name='Tblsearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField()),
                ('cvdata', models.TextField()),
            ],
            options={
                'db_table': 'tblsearch',
            },
        ),
        migrations.CreateModel(
            name='Tblsearchmeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField()),
                ('meta_key', models.CharField(max_length=20)),
                ('meta_value', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tblsearchmeta',
            },
        ),
        migrations.CreateModel(
            name='Tblsector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectorname', models.CharField(max_length=100)),
                ('industry_id', models.IntegerField()),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblsector',
            },
        ),
        migrations.CreateModel(
            name='Tblstates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country_id', models.IntegerField()),
            ],
            options={
                'db_table': 'tblstates',
            },
        ),
        migrations.CreateModel(
            name='Tblsubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('is_active', models.IntegerField()),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblsubjects',
            },
        ),
        migrations.CreateModel(
            name='Tblterrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terrainname', models.CharField(max_length=50)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('modified_by', models.IntegerField()),
                ('modified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblterrain',
            },
        ),
        migrations.CreateModel(
            name='process_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.CharField(blank=True, max_length=255, null=True)),
                ('file_completed', models.CharField(blank=True, max_length=255, null=True)),
                ('total_files', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
