# Generated by Django 4.2.13 on 2024-07-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_information',
            name='completed',
            field=models.BooleanField(default=0),
        ),
    ]
