# Generated by Django 4.2.13 on 2024-07-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_alter_process_information_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_information',
            name='spinner',
            field=models.BooleanField(default=True),
        ),
    ]
