# Generated by Django 4.2.13 on 2024-07-24 05:55

from django.db import migrations, models
import general.tblmodels


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_process_information_spinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='process_information',
            name='files',
            field=models.FileField(blank=True, default=None, null=True, upload_to=general.tblmodels.user_directory_path),
        ),
    ]
