# Generated by Django 4.2.13 on 2024-07-24 07:04

from django.db import migrations, models
import django.db.models.deletion
import general.tblmodels


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_process_information_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=general.tblmodels.user_directory_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='process_information',
            name='files',
        ),
        migrations.AddField(
            model_name='process_information',
            name='mymodel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='general.file_model'),
        ),
    ]
