# Generated by Django 4.2.13 on 2024-07-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_file_model_remove_process_information_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_information',
            name='mymodel',
        ),
        migrations.AddField(
            model_name='file_model',
            name='process',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process', to='general.process_information'),
        ),
    ]
