# Generated by Django 4.2.13 on 2024-07-25 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0008_file_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process_information',
            name='spinner',
        ),
        migrations.CreateModel(
            name='upload_progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.CharField(blank=True, max_length=255, null=True)),
                ('file_completed', models.CharField(blank=True, max_length=255, null=True)),
                ('total_files', models.CharField(blank=True, max_length=255, null=True)),
                ('completed', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
