# Generated by Django 4.2.13 on 2024-07-25 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_remove_process_information_spinner_upload_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_model',
            name='process',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process', to='general.upload_progress'),
        ),
    ]
