# Generated by Django 4.2.13 on 2024-11-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_alter_file_model_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='cvm_run_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField(null=True)),
                ('file_name', models.TextField(max_length=255)),
                ('file_path', models.TextField(null=True)),
                ('status', models.BooleanField(default=1)),
                ('completed', models.BooleanField(null=True)),
                ('duplicate', models.BooleanField(null=True)),
                ('email_not_found', models.BooleanField(default=0, null=True)),
                ('infracon', models.BooleanField(null=True)),
                ('doc_file', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cvm_run_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='education_degree_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'education_degree_new',
                'managed': False,
            },
        ),
    ]
