# Generated by Django 3.2.5 on 2021-08-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gendetails',
            name='email',
        ),
    ]
