# Generated by Django 4.2.13 on 2024-11-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_gendetails_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='genDetails',
        ),
        migrations.DeleteModel(
            name='Tbladdress',
        ),
        migrations.DeleteModel(
            name='Tblcv',
        ),
        migrations.DeleteModel(
            name='Tblcvfiles',
        ),
        migrations.DeleteModel(
            name='Tbleducation',
        ),
    ]
